/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/earth.glb --output src/components/EarthModel.tsx --types --shadows --keepnames 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'


type GLTFResult = {
  nodes: {
    Earth_Diffuse_6K: THREE.Mesh
    Earth_Diffuse_6K001: THREE.Mesh
  }
  materials: {
    Earth_Diffuse_6K: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) { // Use React.ComponentProps<'group'>
  const { nodes, materials } = useGLTF('/models/earth.glb') as unknown as GLTFResult
  return (
    <group dispose={null}>
      <mesh name="Earth_Diffuse_6K" castShadow receiveShadow geometry={nodes.Earth_Diffuse_6K.geometry} material={materials.Earth_Diffuse_6K} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={13.301} />
      <mesh name="Earth_Diffuse_6K001" castShadow receiveShadow geometry={nodes.Earth_Diffuse_6K001.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, -1.414]} scale={13.464} />
    </group>
  )
}

useGLTF.preload('/models/earth.glb')
