/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/jupiter.glb --output src/components/JupiterModel.ts --types --shadows --keepnames 
*/
import React from 'react'; // <-- Added import
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'


type GLTFResult = GLTF & {
  nodes: {
    Куб: THREE.Mesh
    Куб_1: THREE.Mesh
  }
  materials: {
    jupiter: THREE.MeshStandardMaterial
    atmosphere: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/jupiter.glb') as unknown as GLTFResult
  return (
    <group dispose={null}>
      <mesh name="Куб" castShadow receiveShadow geometry={nodes.Куб.geometry} material={materials.jupiter} />
      <mesh name="Куб_1" castShadow receiveShadow geometry={nodes.Куб_1.geometry} material={materials.atmosphere} />
    </group>
  )
}

useGLTF.preload('/models/jupiter.glb')
