/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/jupiter.glb --output src/components/JupiterModel.tsx --types --shadows --keepnames --transform 
Files: public/models/jupiter.glb [4.53MB] > J:\cosmic-journey-secondbackup\src\components\jupiter-transformed.glb [141.12KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Jupiter: THREE.Mesh
  }
  materials: {
    Jupiter: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/jupiter.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Jupiter" castShadow receiveShadow geometry={nodes.Jupiter.geometry} material={materials.Jupiter} position={[0, -0.802, -12.507]} scale={70} />
    </group>
  )
}

useGLTF.preload('/models/jupiter.glb')
