/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mercury.glb --output src/components/MercuryModel.tsx --types --shadows --keepnames --transform 
Files: public/models/mercury.glb [16.49MB] > J:\cosmic-journey-secondbackup\src\components\mercury-transformed.glb [196.6KB] (99%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mercury: THREE.Mesh
  }
  materials: {
    Mercury: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/mercury.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Mercury" castShadow receiveShadow geometry={nodes.Mercury.geometry} material={materials.Mercury} position={[0, 1, 2.743]} scale={9.8} />
    </group>
  )
}

useGLTF.preload('/models/mercury.glb')
