/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mercury.glb --output src/components/MercuryModel.tsx --types --shadows --keepnames 
*/

import React from 'react'; // Added React import
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';

type GLTFResult = {
  nodes: {
    Куб: THREE.Mesh
    Куб_1: THREE.Mesh
  }
  materials: {
    mercury: THREE.MeshStandardMaterial
    atmosphere: THREE.MeshStandardMaterial
  }
};

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/mercury.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh name="Куб" castShadow receiveShadow geometry={nodes.Куб.geometry} material={materials.mercury} />
      <mesh name="Куб_1" castShadow receiveShadow geometry={nodes.Куб_1.geometry} material={materials.atmosphere} />
    </group>
  );
}

useGLTF.preload('/models/mercury.glb');
