/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/neptune.glb --output src/components/NeptuneModel.tsx --types --shadows --keepnames 
*/

import React from 'react'; // Add React import
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'

// Simplify GLTFResult type (remove GLTF &, remove animations)
type GLTFResult = {
  nodes: {
    neptune: THREE.Mesh; // Correct name based on console log
  }
  materials: {
    NeptuneTexture: THREE.MeshStandardMaterial // Adjust based on actual model
  }
};

export function Model(props: React.ComponentProps<'group'>) { // Change to React.ComponentProps
  const { nodes, materials } = useGLTF('/models/neptune.glb') as unknown as GLTFResult; // Fix path and add type assertion
  
  console.log("--- Neptune Model Nodes ---", nodes);
  
  return (
    <group {...props} dispose={null}>
      <mesh
        name="neptune"
        castShadow
        receiveShadow
        geometry={nodes.neptune.geometry}
        material={materials.NeptuneTexture}
      />
    </group>
  );
}

useGLTF.preload('/models/neptune.glb'); // Fix path here too
