/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/sun.glb --output src/components/SunModel.tsx --types --shadows --keepnames 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'


type GLTFResult = {
  nodes: {
    sun1: THREE.Mesh
  }
  materials: {
    sun: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) { // Use React.ComponentProps<'group'>
  const { nodes, materials } = useGLTF('/models/sun.glb') as unknown as GLTFResult
  return (
    <group dispose={null}>
      <group name="Solar_system" scale={37.466}>
        <mesh name="sun1" castShadow receiveShadow geometry={nodes.sun1.geometry} material={materials.sun} scale={0.267} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/sun.glb')
