/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/uranus.glb --output src/components/UranusModel.tsx --types --shadows --keepnames 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'

type GLTFResult = {
  nodes: {
    // Use the names from YOUR console log:
    Куб: THREE.Mesh;
    Куб_1: THREE.Mesh;
    Куб_2: THREE.Mesh;
  };
  materials: {
    UranusTexture: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/uranus.glb') as unknown as GLTFResult
  
  console.log("--- Uranus Model Nodes ---", nodes);
  
  return (
    <group {...props} dispose={null}>
      <mesh 
        name="Куб" 
        castShadow 
        receiveShadow 
        geometry={nodes.Куб.geometry} 
        material={materials.UranusTexture} 
      />
      <mesh 
        name="Куб_1" 
        castShadow 
        receiveShadow 
        geometry={nodes.Куб_1.geometry} 
        material={materials.UranusTexture} 
      />
      <mesh 
        name="Куб_2" 
        castShadow 
        receiveShadow 
        geometry={nodes.Куб_2.geometry} 
        material={materials.UranusTexture} 
      />
    </group>
  )
}

useGLTF.preload('/models/uranus.glb')
