/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/venus.glb --output src/components/VenusModel.tsx --types --shadows --keepnames --transform 
Files: public/models/venus.glb [13.98MB] > J:\cosmic-journey-secondbackup\src\components\venus-transformed.glb [181.22KB] (99%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Venus: THREE.Mesh
  }
  materials: {
    Venus: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/venus.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Venus" castShadow receiveShadow geometry={nodes.Venus.geometry} material={materials.Venus} position={[0, 1, 0.872]} scale={24} />
    </group>
  )
}

useGLTF.preload('/models/venus.glb')
