// Log AFTER attempting manual load
console.log("--- All Environment Variables (After Manual dotenv Load) ---", process.env);

import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(request: VercelRequest, response: VercelResponse) {
  const { planet } = request.query;
  const apiKey = process.env.OPENAI_API_KEY;

  console.log("--- Planet Description Handler ---");
  console.log(`OpenAI Key found: ${!!apiKey}`);
  console.log(`Planet requested: ${planet}`);

  if (!planet || typeof planet !== 'string') {
    console.error("Description: Missing planet parameter");
    return response.status(400).json({ error: 'Planet parameter is required' });
  }

  if (!apiKey) {
    console.error("Description: API key missing");
    return response.status(500).json({ error: 'OpenAI API key is not configured' });
  }

  try {
    // Enhanced planet descriptions with interesting facts and "Did you know" sections
    console.log("Description: Returning enhanced planet descriptions");
    const descriptions = {
      mercury: "Mercury is the smallest and innermost planet in our Solar System, completing an orbit around the Sun every 88 Earth days. Its surface is heavily cratered and resembles our Moon due to the lack of atmosphere to weather the impacts. Mercury experiences extreme temperature variations, with scorching 800°F (430°C) days and frigid -290°F (-180°C) nights. Its iron core makes up about 60% of its mass, creating a magnetic field about 1% as strong as Earth's. The planet's orbit is highly eccentric, causing unique sunrise patterns where the Sun briefly rises, sets, and rises again. Did you know? A single day on Mercury (from one sunrise to the next) lasts about 176 Earth days!",
      
      venus: "Venus is Earth's closest planetary neighbor and the second planet from the Sun, often called Earth's 'sister planet' due to similar size and mass. However, Venus is a world of extremes with a thick, toxic atmosphere composed mainly of carbon dioxide that traps heat in a runaway greenhouse effect. The surface temperature reaches a scorching 900°F (475°C), hot enough to melt lead. Venus rotates backwards compared to other planets, with its sun rising in the west and setting in the east. Massive volcanic plains cover 80% of the surface, with thousands of volcanoes larger than 20km dotting the landscape. Did you know? A day on Venus is longer than its year—it takes 243 Earth days to rotate once but only 225 Earth days to orbit the Sun!",
      
      earth: "Earth is the third planet from the Sun and the only astronomical object known to harbor life. Our planet's dynamic surface is 71% covered by oceans of liquid water essential for life, with the remaining 29% consisting of continents and islands. Earth's atmosphere is primarily nitrogen and oxygen, protected from solar radiation by the ozone layer. The planet's magnetic field, generated by its iron-nickel core, shields the surface from harmful solar winds. Earth's axial tilt of 23.5 degrees creates our seasons as different hemispheres receive varying amounts of sunlight throughout its 365.25-day orbit. Did you know? Earth is not a perfect sphere—it bulges at the equator and is slightly flattened at the poles due to its rotation!",
      
      mars: "Mars, the fourth planet from the Sun, is known as the 'Red Planet' due to iron oxide (rust) that dominates its surface. It features the largest volcano in the solar system, Olympus Mons, standing nearly three times taller than Mount Everest, and Valles Marineris, a canyon system that would stretch from New York to California if on Earth. Mars has two small moons, Phobos and Deimos, thought to be captured asteroids. The planet experiences seasons similar to Earth due to its comparable axial tilt of 25 degrees, with polar ice caps that grow and recede with the seasons. Did you know? Mars has the most dramatic dust storms in the solar system, occasionally engulfing the entire planet for months at a time!",
      
      jupiter: "Jupiter, the fifth and largest planet in our Solar System, is a gas giant with a mass two and a half times that of all other planets combined. Its iconic feature, the Great Red Spot, is a storm that has been raging for at least 400 years and is large enough to contain two or three Earths. Jupiter's atmosphere consists primarily of hydrogen and helium, creating colorful bands and swirls as different gases rise and fall. The planet has a powerful magnetic field 14 times stronger than Earth's and at least 79 moons, including the four large Galilean moons: Io, Europa, Ganymede, and Callisto. Did you know? Jupiter rotates faster than any other planet, completing a day in just under 10 hours despite its enormous size!",
      
      saturn: "Saturn, the sixth planet from the Sun, is instantly recognizable by its magnificent ring system spanning up to 175,000 miles (282,000 km) in diameter but only about 30 feet (10 meters) thick. These rings consist of countless ice particles ranging from microscopic dust to house-sized chunks, possibly remnants of a destroyed moon. Saturn is the least dense planet in our solar system—so light it would float in water if there were an ocean large enough to hold it. The gas giant has at least 83 moons, with Titan being the second-largest moon in the solar system and the only one with a substantial atmosphere. Did you know? Saturn's hexagonal cloud pattern at its north pole is a unique, persistent six-sided jet stream large enough to fit four Earths inside!",
      
      uranus: "Uranus, the seventh planet from the Sun, is an ice giant with a unique sideways rotation—it essentially rolls around the Sun on its side with an axial tilt of 98 degrees. This unusual orientation causes extreme 42-year-long seasons where parts of the planet experience 21 years of continuous sunlight followed by 21 years of darkness. Uranus appears as a featureless blue-green sphere due to methane in its atmosphere absorbing red light. Beneath its atmosphere lies an ocean of water, ammonia, and methane ices. The planet has 13 known rings and 27 known moons, all named after characters from the works of Shakespeare and Alexander Pope. Did you know? Uranus is the only planet named after a Greek deity (Ouranos) rather than a Roman one!",
      
      neptune: "Neptune, the eighth and farthest known planet from the Sun, is a dynamic ice giant with the strongest winds in the solar system—reaching supersonic speeds of over 1,200 mph (2,000 km/h). Its deep blue color results from methane in the atmosphere absorbing red light. Neptune was the first planet located through mathematical predictions rather than direct observation, discovered in 1846. The planet experiences seasons lasting over 40 years due to its 165-year orbit around the Sun. Neptune's largest moon, Triton, orbits backwards compared to the planet's rotation and is one of the coldest objects in our solar system at -391°F (-235°C). Did you know? Neptune has only been visited by one spacecraft, Voyager 2, which flew by in 1989 and revealed the presence of the Great Dark Spot, a storm system the size of Earth!",
      
      pluto: "Pluto, reclassified as a dwarf planet in 2006, orbits in the distant Kuiper Belt beyond Neptune. Despite its small size—only about two-thirds the diameter of Earth's Moon—Pluto has captured public imagination since its discovery in 1930. Its highly eccentric orbit occasionally brings it closer to the Sun than Neptune, last occurring from 1979 to 1999. Pluto has a thin atmosphere that expands when closer to the Sun and collapses as it moves away. The New Horizons mission revealed a surprisingly complex world with a heart-shaped region (Tombaugh Regio) of nitrogen ice, mountain ranges, and evidence of ancient rivers and lakes of liquid nitrogen. Did you know? Pluto and its largest moon, Charon, are so close in size that they orbit around a point between them, essentially forming a double dwarf planet system!"
    };
    
    const planetKey = planet.toLowerCase() as keyof typeof descriptions;
    const description = descriptions[planetKey] || `Test description for ${planet}: A fascinating celestial body in our cosmic neighborhood with unique characteristics that make it stand out in our solar system. Scientists continue to study this world to uncover its mysteries and understand its place in the cosmos. Did you know? Each new discovery about ${planet} helps us better understand the formation and evolution of our solar system!`;
    
    return response.status(200).json({ description });
  } catch (error: any) {
    console.error("Description: Error occurred", error);
    return response.status(500).json({ 
      error: error.message || 'Internal server error while fetching planet description'
    });
  }
}
